Repository jenkinsci/saferestart-plugin, pull requests merged in 2025-01, with the labels that each got.

#46 Require 2.452.4
  pom.xml
Labels: chore

#47 Use reload symbol instead of png icon
  docs/images/restart_admin.png
  docs/images/restart_side.png
  src/main/java/org/jenkins/ci/plugins/saferestart/Constants.java
  src/main/java/org/jenkins/ci/plugins/saferestart/SafeRestartManagementLink.java
  src/main/java/org/jenkins/ci/plugins/saferestart/SafeRestartRootAction.java
  src/main/webapp/images/24x24/quick_restart.png
  src/main/webapp/images/48x48/quick_restart.png
  src/main/webapp/images/readme.txt
Labels: rfe

#49 Add CODEOWNERS for easier work with GitHub reviews
  .github/CODEOWNERS
Labels: chore

#50 Simplify test initialization method and give it a better name
  src/test/java/org/jenkins/ci/plugins/saferestart/SafeRestartRootActionTest.java
Labels: test

#51 Enable automated release
  .github/workflows/cd.yaml
  .github/workflows/release-drafter.yml
  .mvn/maven.config
  pom.xml
Labels: rfe
